//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int BannerID { get; set; }
        public string BannerTitle { get; set; }
        public string Description { get; set; }
        public string PictureUrl { get; set; }
    }
}
