//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcategory
    {
        public int SubcategoryID { get; set; }
        public int ParentID { get; set; }
        public string SubcategoryName { get; set; }
        public string Description { get; set; }
        public string PictureUrl { get; set; }
        public short Status { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
